spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${EMAIL_USERNAME:oficina.fiap@gmail.com}
    password: ${EMAIL_PASSWORD:senha-app}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    test-connection: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 5
    initial-instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:notification-service}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${server.port}

server:
  port: ${SERVER_PORT:8087}

app:
  notification:
    email:
      sender: ${EMAIL_SENDER:oficina.fiap@gmail.com}

logging:
  level:
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
