apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
type: Opaque
stringData:
  JWT_SECRET: PROD-JWT-SECRET-MINIMUM-256-BITS-REPLACE-ME  # SUBSTITUIR POR VALOR REAL VIA CI/CD

---
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
type: Opaque
stringData:
  EMAIL_HOST: smtp.gmail.com
  EMAIL_PORT: "587"
  EMAIL_USERNAME: PROD-EMAIL-REPLACE-ME  # SUBSTITUIR POR VALOR REAL VIA CI/CD
  EMAIL_PASSWORD: PROD-EMAIL-PASSWORD-REPLACE-ME  # SUBSTITUIR POR VALOR REAL VIA CI/CD
  EMAIL_FROM: PROD-EMAIL-REPLACE-ME  # SUBSTITUIR POR VALOR REAL VIA CI/CD
