apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oficina-ingress
  namespace: oficina
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: oficina.local
      http:
        paths:
          - path: /eureka
            pathType: Prefix
            backend:
              service:
                name: eureka-server
                port:
                  number: 8761
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 8082
          - path: /customer
            pathType: Prefix
            backend:
              service:
                name: customer-service
                port:
                  number: 8081
          - path: /catalog
            pathType: Prefix
            backend:
              service:
                name: catalog-service
                port:
                  number: 8083
          - path: /inventory
            pathType: Prefix
            backend:
              service:
                name: inventory-service
                port:
                  number: 8084
          - path: /budget
            pathType: Prefix
            backend:
              service:
                name: budget-service
                port:
                  number: 8085
          - path: /work-order
            pathType: Prefix
            backend:
              service:
                name: work-order-service
                port:
                  number: 8086
          - path: /notification
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8087
