apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  namespace: oficina
type: Opaque
stringData:
  EMAIL_USERNAME: oficina.fiap@gmail.com
  EMAIL_PASSWORD: senha-app
  EMAIL_SENDER: oficina.fiap@gmail.com
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: "587"
