# Profile para Docker Compose
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/oficina-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  sql:
    init:
      mode: always

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 5
    initial-instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:customer-service}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
