spring:
  application:
    name: eureka-server

server:
  port: ${SERVER_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
    response-cache-update-interval-ms: 5000
    response-cache-auto-expiration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: http://auth-service:8082/v3/api-docs
      - name: Customer Service
        url: http://customer-service:8081/v3/api-docs
      - name: Catalog Service
        url: http://catalog-service:8083/v3/api-docs
      - name: Inventory Service
        url: http://inventory-service:8084/v3/api-docs
      - name: Budget Service
        url: http://budget-service:8085/v3/api-docs
      - name: Work Order Service
        url: http://work-order-service:8086/v3/api-docs
      - name: Notification Service
        url: http://notification-service:8087/v3/api-docs
    path: /swagger-ui.html
    display-request-duration: true
    filter: true
  show-actuator: false

logging:
  level:
    root: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
