server:
  port: ${SERVER_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:eureka-server}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
    response-cache-update-interval-ms: 5000
    response-cache-auto-expiration-in-seconds: 30

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: https://d6l9d5prg2.execute-api.us-east-2.amazonaws.com/auth/v3/api-docs
      - name: Customer Service
        url: https://d6l9d5prg2.execute-api.us-east-2.amazonaws.com/customer/v3/api-docs
      - name: Catalog Service
        url: https://d6l9d5prg2.execute-api.us-east-2.amazonaws.com/catalog/v3/api-docs
      - name: Inventory Service
        url: https://d6l9d5prg2.execute-api.us-east-2.amazonaws.com/inventory/v3/api-docs
      - name: Budget Service
        url: https://d6l9d5prg2.execute-api.us-east-2.amazonaws.com/budget/v3/api-docs
      - name: Work Order Service
        url: https://d6l9d5prg2.execute-api.us-east-2.amazonaws.com/work-order/v3/api-docs
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
