apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oficina-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: dev.oficina-mecanica.com  # Ajuste para seu dom√≠nio dev
      http:
        paths:
          # Rotas com prefixo /dev
          - path: /dev/eureka(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: eureka-server-internal
                port:
                  number: 8761

          - path: /dev/auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 8082

          - path: /dev/customer(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: customer-service
                port:
                  number: 8081

          - path: /dev/catalog(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: catalog-service
                port:
                  number: 8083

          - path: /dev/inventory(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: inventory-service
                port:
                  number: 8084

          - path: /dev/budget(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: budget-service
                port:
                  number: 8085

          - path: /dev/work-order(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: work-order-service
                port:
                  number: 8086

          - path: /dev/notification(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notification-service
                port:
                  number: 8087
